### ISSUE TITLE
Internal functions appear in API docs

### ISSUE THREAD

**Issue by guenp** [MicrosoftDocs/quantum-api#5]
It looks like internal functions are added to our public API documentation.

See below for example.

Tag: @cgranade @KittyYeungQ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83db2f0e-fd61-7881-7cd4-41f9925cfd79
* Version Independent ID: fcc0bd04-8cb3-b1fa-7839-3c093fddceb5
* Content: [UpdatedOutputPattern function - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.synthesis.updatedoutputpattern)
* Content Source: [api/qsharp/microsoft.quantum.synthesis.updatedoutputpattern.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/api/qsharp/microsoft.quantum.synthesis.updatedoutputpattern.md)
* Product: **quantum**
* GitHub Login: @ricardo-espinoza

**Comment by cgranade** [comment]
I'm not finding it at the moment, but we had a qsharp-compiler issue open for that as per your previous report. The issue has since been fixed, but we decided not to include that fix in the previous release or any of its hotfixes; as a result, the fix should land in the next release when API docs are next published.
